# Generated by Django 5.2.6 on 2025-10-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image', max_length=200)),
                ('is_main', models.BooleanField(default=False, help_text='Is this the main image?')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full product name (e.g., 'Dell XPS 13 2021')", max_length=300)),
                ('brand', models.CharField(help_text="Brand name (e.g., 'Dell', 'Apple')", max_length=200)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('smartphone', 'Smartphone'), ('accessory', 'Accessory')], default='laptop', help_text='Product category', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in rupees (e.g., 99999.99)', max_digits=10)),
                ('short_description', models.TextField(help_text='A concise summary for the list view')),
                ('long_description', models.TextField(blank=True, help_text='Detailed product description', null=True)),
                ('processor', models.CharField(blank=True, help_text="Processor details (e.g., 'Intel i7-1165G7')", max_length=200)),
                ('ram_gb', models.CharField(blank=True, help_text="RAM size (e.g., '16GB')", max_length=100)),
                ('storage', models.CharField(blank=True, help_text="Storage details (e.g., '512GB SSD')", max_length=200)),
                ('display', models.CharField(blank=True, help_text="Display details (e.g., '13.3 inch FHD')", max_length=200)),
                ('os', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('chromeos', 'ChromeOS'), ('ios', 'iOS'), ('other', 'Other')], default='windows', help_text='Operating System', max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms (e.g., 1.2)', max_digits=5, null=True)),
                ('main_image', models.ImageField(help_text='Main product image URL', upload_to='products/')),
                ('slug', models.SlugField(blank=True, help_text="Unique URL-friendly identifier (e.g., 'dell-xps-13-2021')", max_length=200, unique=True)),
                ('images', models.ManyToManyField(blank=True, help_text='Additional product images', related_name='products', to='main.image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
