# Generated by Django 5.2.6 on 2025-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unique URL-friendly identifier (e.g., 'dell-xps-13-2021')", max_length=200, unique=True),
        ),
    ]
